#!/bin/bash
task=${1}
make CPPFLAGS='-Wall -g' ${task}
if [ $? -ne 0 ] ; then 
    exit;
fi

IN=${task}.in

if [ ! -f $IN ] ; then 
    exit; 
fi

OUT=/tmp/myout.txt
LINES=`tput lines`

if [ -f $OUT ] ; then rm /tmp/myout.txt; fi

echo "running ${task} < $IN"
./${task} < $IN > $OUT && diff -w -q ${task}.out $OUT || echo run " vimdiff $OUT ${task}.out" to see diff

#could just use more $OUT, but more does not clear the visual when it returns
if [ `wc -l $OUT | awk '{print $1}' ` -gt $((LINES-5)) ] ; then
    less -e $OUT;
else
    cat $OUT;
fi

